logging:
  config: classpath:logback.xml

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.handsome.leave.entity

server:
  port: 8080

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      password: handsome
      url: jdbc:mysql://127.0.0.1:3306/db_oke?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai
      username: handsome
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    time-zone: Asia/Shanghai
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    timeout: 3000
